everit-org/json-schema

- tests/src/test/java/org/everit/json/schema/IssueTest.java
- tests/src/test/resources/org/everit/json/schema/issues/issue36/expectedException.json
- tests/src/test/resources/org/everit/json/schema/issues/issue36/schema.json
- tests/src/test/resources/org/everit/json/schema/issues/issue36/subject-invalid.json
As discussed in Issue 36, I implemented the ability for a user to add an issue testcase and specify the exact validation failures that they are expecting to be generated by the library.  Along with these changes, I am submitting three new files under issue36/ that demonstrate the new functionality.  Note that the subject JSON file contains 4 validation failures. The library correctly finds all 4, but the top level summary message incorrectly states "3 validation failures".  This is a potential bug, to be determined by the maintainer based on the design of the library... see what you think. 
See the TODO comments also.  These are utility methods I added to IssueTest (processValidationFailures(), loadJsonFile()) that could be moved into the core project, so that users could use them as …
> Allow users to specify expected values for validation failures

- core/pom.xml
- core/src/main/java/org/everit/json/schema/ArraySchema.java
- core/src/main/java/org/everit/json/schema/BooleanSchema.java
- core/src/main/java/org/everit/json/schema/CombinedSchema.java
- core/src/main/java/org/everit/json/schema/EmptySchema.java
- core/src/main/java/org/everit/json/schema/EnumSchema.java
- core/src/main/java/org/everit/json/schema/NotSchema.java
- core/src/main/java/org/everit/json/schema/NullSchema.java
- core/src/main/java/org/everit/json/schema/NumberSchema.java
- core/src/main/java/org/everit/json/schema/ObjectSchema.java
- core/src/main/java/org/everit/json/schema/ReferenceSchema.java
- core/src/main/java/org/everit/json/schema/Schema.java
- core/src/main/java/org/everit/json/schema/StringSchema.java
- core/src/test/java/org/everit/json/schema/ArraySchemaTest.java
- core/src/test/java/org/everit/json/schema/BooleanSchemaTest.java
- core/src/test/java/org/everit/json/schema/CombinedSchemaTest.java
- core/src/test/java/org/everit/json/schema/EmptySchemaTest.java
- core/src/test/java/org/everit/json/schema/EnumSchemaTest.java
- core/src/test/java/org/everit/json/schema/NotSchemaTest.java
- core/src/test/java/org/everit/json/schema/NullSchemaTest.java
- core/src/test/java/org/everit/json/schema/NumberSchemaTest.java
- core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java
- core/src/test/java/org/everit/json/schema/ReferenceSchemaTest.java
- core/src/test/java/org/everit/json/schema/StringSchemaTest.java
This makes the derived schema classes final. This could break backward compatibility. If needed, that can be relaxed.
fixes #49
> add equals and hashcode for schema objects

- core/src/main/java/org/everit/json/schema/ValidationException.java
- core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java
- core/src/test/java/org/everit/json/schema/TestSupport.java
- core/src/test/resources/org/everit/jsonvalidator/objecttestcases.json
`ValidationException#getAllMessages()` walks through all nested violations and return the list of error messages. This is particularly useful for use by a REST API when validating the schema of an incoming JSON payload. The flat list of messages provides a convenient format for clients to log, and even parse, the errors.
I also added a unit test to verify existing and new behavior for multiple nested schema violations.
> Add ValidationException#getAllMessages() for collecting nested error messages

- core/src/main/java/org/everit/json/schema/StringSchema.java
- tests/src/test/resources/org/everit/json/schema/draft4/maxLength.json
- tests/src/test/resources/org/everit/json/schema/draft4/minLength.json
The test suite had the wrong expected values for max/minLength for unicode strings, they've been updated. See: [draft4/minLength.json#29](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/develop/tests/draft4/minLength.json#L29) and [draft4/maxLength#29](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/develop/tests/draft4/maxLength.json#L29)
Use the number of unicode codepoints to compare lengths.  see: [stackoverflow](http://stackoverflow.com/questions/6828076/how-to-correctly-compute-the-length-of-a-string-in-java)
Why was the test suite logic flipped? Old data? Perhaps looking into importing the test suite as git submodule would be a good idea?
> Fix unicode length comparisons

- core/pom.xml
```
$ mvn clean
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.everit.json:org.everit.json.schema:bundle:1.4.1
[WARNING] 'build.plugins.plugin.version' fororg.apache.felix:maven-bundle-plugin is missing. @ line 57, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because theythreaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
The (sub) module `core` did not reference the parent POM thus the version from the (transitive) parent `org.everit.config:org.everit.config.main` is not available. The version used is `3.0.0`.
Apply quick fix by adding mandatory `<version/>`. The …
> missing version for `org.apache.felix:maven-bundle-plugin`

- .travis.yml
- README.md
- core/pom.xml
As discussed/proposed in #69 enable code coverage reporting on [Coveralls.io](https://coveralls.io).
@erosb before you accept this PR you can [have a look](https://coveralls.io/github/agebhar1/json-schema) how it will be. Sign in with your GitHub account on [Coveralls.io](https://coveralls.io) and enable this repository - maybe you must (re)sync with GitHub if it does not appear on the site. The configuration for Travis CI is updated and the badge for code coverage on `master` branch is also added.
Congrats for this code coverage!
> enable code coverage reporting on Coveralls.io

- core/pom.xml
Update to latest version 1.6 [1].
[1] https://commons.apache.org/proper/commons-validator/changes-report.html#a1.6
> update »Apache Commons Validator« to 1.6

- core/src/main/java/org/everit/json/schema/NumberSchema.java
- core/src/test/java/org/everit/json/schema/NumberSchemaTest.java
It is stated that [Starting from version 1.1.0 the validator collects every schema violations (instead of failing immediately on the first one)](https://github.com/everit-org/json-schema#investigating-failures), but for some reason it was not like that for NumberSchema. This PR addressed this minor issue by introducing instance field with the list of violations.
> Collect all violations while validating NumberSchema

- core/src/main/java/org/everit/json/schema/internal/URIV4FormatValidator.java
- core/src/main/java/org/everit/json/schema/loader/SpecificationVersion.java
- core/src/test/java/org/everit/json/schema/internal/DefaultFormatValidatorTest.java
- core/src/test/java/org/everit/json/schema/loader/SchemaLoaderTest.java
- tests/src/test/resources/org/everit/json/schema/draft4/format.json
Allow relative references as URIs in draft 4 validation.
Fixes #132
> ARUHA-1275 Fix URI validation

- core/src/main/java/org/everit/json/schema/ArraySchemaValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/ObjectSchemaValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/Schema.java
- core/src/main/java/org/everit/json/schema/StringSchemaValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/ValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/loader/LoaderConfig.java
- core/src/main/java/org/everit/json/schema/loader/SchemaLoader.java
- core/src/test/java/org/everit/json/schema/ArraySchemaTest.java
- core/src/test/java/org/everit/json/schema/NullableValidationTest.java
- core/src/test/java/org/everit/json/schema/NumberSchemaTest.java
- core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java
- core/src/test/java/org/everit/json/schema/StringSchemaTest.java
- core/src/test/java/org/everit/json/schema/ValidatingVisitorTest.java
- core/src/test/java/org/everit/json/schema/loader/SchemaLoaderTest.java
- core/src/test/resources/org/everit/jsonvalidator/testschemas.json
This PR is an implementation of the [nullable keyword of OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaNullable) which is not the part of any json schema spec versions.
The feature does not work out of the box and should be explicitly turned on by calling `SchemaLoaderBuilder#nullableSupport(true)` before loading the schema.
> Nullable support

- core/src/main/java/org/everit/json/schema/StringSchema.java
- core/src/test/java/org/everit/json/schema/StringSchemaTest.java
- fix NPE for `null` pattern when calling `getPattern()`
- increasing code coverage a tiny bit
related to issue #147
> fix NPE when calling getPattern()

- core/pom.xml
- core/src/main/java/org/everit/json/schema/StringSchema.java
- core/src/main/java/org/everit/json/schema/StringSchemaValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/Visitor.java
- core/src/main/java/org/everit/json/schema/loader/LoaderConfig.java
- core/src/main/java/org/everit/json/schema/loader/SchemaLoader.java
- core/src/main/java/org/everit/json/schema/loader/StringSchemaLoader.java
- core/src/main/java/org/everit/json/schema/regexp/JavaUtilRegexpFactory.java
- core/src/main/java/org/everit/json/schema/regexp/RE2JRegexpFactory.java
- core/src/main/java/org/everit/json/schema/regexp/Regexp.java
- core/src/main/java/org/everit/json/schema/regexp/RegexpFactory.java
- core/src/main/java/org/everit/json/schema/regexp/RegexpMatchingFailure.java
- core/src/test/java/org/everit/json/schema/StringSchemaTest.java
- core/src/test/java/org/everit/json/schema/regexp/JavaUtilRegexpTest.java
- core/src/test/java/org/everit/json/schema/regexp/RE2JRegexpTest.java
- pom.xml
- tests/pom.xml
- tests/src/test/java/org/everit/json/schema/IssueTest.java
- tests/src/test/resources/org/everit/json/schema/issues/issue147/validator-config.json
This PR partially reverts #147 , fixes the regression reported in #156 and #157 .
The issue was that the RE2J library doesn't support all possible regular expressions that `java.util.regex` does (at least not the ones ontaining lookaheads).
This is solved by 
* creating an abstraction layer of regexp solutions, this is the `org.everit.json.schema.regexp` package
* making the implementation configurable via the  `SchemaLoaderBuilder#regexpFactory(RegexpFactory)` method
* the default implementation uses the `java.util.regex.Pattern` class, so backward-compatibility is restored
* people who need re2j can use the `RE2JRegexpFactory` implementation
> Making RegExp implementation configurable

- core/pom.xml
- core/src/main/java/org/everit/json/schema/ObjectSchema.java
- core/src/main/java/org/everit/json/schema/ObjectSchemaValidatingVisitor.java
- core/src/main/java/org/everit/json/schema/Visitor.java
- core/src/main/java/org/everit/json/schema/loader/ObjectSchemaLoader.java
- core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java
- core/src/test/java/org/everit/json/schema/loader/DefinesPropertyTest.java
- core/src/test/resources/org/everit/jsonvalidator/testschemas.json
- pom.xml
- tests/pom.xml
Changing `ObjectSchema` to represent `patternProperties` as a `Map<Regexp, Schema>` instead of `Map<Pattern, Schema>`
This is a follow-up change of introducing `Regexp` and `RegexpFactory` interfaces in `1.9.0`.
Keeping but deprecating existing accessor & builder methods of `ObjectSchema` which consume / return a `Pattern`, converting from/to `Regexp`.
In the end, changing `ObjectSchemaLoader` to instantiate a `Regexp` instance using the configured `RegexpFactory` instead of attempting to use RE2J directly.
Also bumping version number to 1.9.1, since it is going to be a quick bugfix release ASAP.
> Fixing regex handling in `"patternProperties"`

- core/pom.xml
Hello!
There were maven dependency conflicts for artifacts:
- commons-collections
- commons-logging
- hamcrest-core
They were resolved in pom-file.
Thanks.
> Fix Maven dependency's conflicts

- core/pom.xml
Currently, IntelliJ and other IDEs aren't able to automatically jump to source or documentation for this library, since those jars aren't published.
We should get a nice developer experience improvement by providing these jars. This PR follows the example plugin configuration in https://github.com/jitpack/maven-simple
> Publish sources jar and javadoc jar

- core/src/main/java/org/everit/json/schema/loader/SpecificationVersion.java
- core/src/test/java/org/everit/json/schema/loader/SchemaLoaderTest.java
- core/src/test/resources/org/everit/jsonvalidator/https-schema-uri.json
Fixes Issue #306 
Schemas hosted on json-schema.org can be accessed at both HTTP and HTTPS endpoints. The current inference logic for schema versions caused SchemaException if HTTPS endpoint was used in the $schema
> [Issue #306] Supports HTTPS endpoint for version inference

- core/src/main/java/org/everit/json/schema/loader/ClassPathAwareSchemaClient.java
- core/src/test/java/org/everit/json/schema/loader/ClassPathAwareSchemaClientTest.java
Currently, if you reference a schema file that does not exist, you get this error message:
```
unknown protocol: classpath
```
because the `classpath` URL is being passed to the fallback client, which can't process it.
This PR improves the error message to name the classpath resource that cannot be found:
```
Caused by: java.io.IOException: Could not find classpath://com/test/predefined.json
```
> error handling for classpath schema client

- core/src/main/java/org/everit/json/schema/loader/JsonPointerEvaluator.java
- core/src/test/java/org/everit/json/schema/loader/JsonPointerEvaluatorTest.java
Fixing #407: incorrect SchemaException#schemaLocation when a remote shema fails to parse.
> Fixing #407

- core/src/main/java/org/everit/json/schema/loader/SpecificationVersion.java
> Add support for non-dialect specific schema URLs

- core/pom.xml
- core/src/main/java/org/everit/json/schema/loader/SpecificationVersion.java
- core/src/test/java/org/everit/json/schema/ValidatingVisitorTest.java
- core/src/test/java/org/everit/json/schema/loader/JsonObjectTest.java
- core/src/test/java/org/everit/json/schema/loader/JsonValueTest.java
- core/src/test/java/org/everit/json/schema/loader/ProjectedJsonObjectTest.java
- core/src/test/java/org/everit/json/schema/loader/internal/TypeBasedMultiplexerTest.java
Hi @erosb,
please be patient with me as this is my first contribution to an OpenSource project. I checked the [contributing guidelines](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md), but I raise a PR not actually for a bug report - I just would like to upgrade the dependencies. 
The OWASP Dependency check reported issues that I tracked down being being the [Guava Library](https://mvnrepository.com/artifact/com.google.guava/guava) in Version [29.0-jre](https://mvnrepository.com/artifact/com.google.guava/guava/29.0-jre) being vulnerble to [CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908), which is referenced in [json-schema/core/pom.xml](https://github.com/GittiMcHub/json-schema/blob/13716721902f5db86c0d2603c26a21fe927c4ded/core/pom.xml#L2 …
> Upgrade Guava dependency due CVE 2020-8908 and other library upgrades

- core/pom.xml
The new version addresses CVE-2022-45688
> Upgrade org.json version

- core/pom.xml
Please update the org.json dependency to address CVE-2023-5072.
This is a simple dependency version bump. @erosb this can be quickly merged
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.everit.json.schema.parent 0.0.0-develop:
[INFO] 
[INFO] everit-org/json-schema ............................. SUCCESS [ 22.433 s]
[INFO] org.everit.json.schema.parent ...................... SUCCESS [  0.024 s]
[INFO] org.everit.json.schema.tests.parent ................ SUCCESS [  0.005 s]
[INFO] org.everit.json.schema.tests.vanilla ............... SUCCESS [  7.891 s]
[INFO] org.everit.json.schema.tests.android ............... SUCCESS [  7.136 s]
[INFO] org.everit.json.schema.tests.slim .................. SUCCESS [  6.753 s]
[INFO] …
> update org.json to address CVE-2023-5072

- core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java
Created this PR to fix 1 flaky test - [multipleSchemaDepViolation](https://github.com/everit-org/json-schema/blob/master/core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java#L118)
--------------
1. **How were these test identified as flaky?**
This test was identified as flaky by using an open-source research tool named [NonDex](https://github.com/TestingResearchIllinois/NonDex) which is responsible for finding and diagnosing non-deterministic runtime exceptions in Java programs.
2. **What was the error?**
The test uses `e.getCausingExceptions()` and acknowledges that getCausingExceptions() is non-deterministic and may give swapped order and thus, the test swaps the 0th and 1st element [here](https://github.com/everit-org/json-schema/blob/master/core/src/test/java/org/everit/json …
> Fixed multipleSchemaDepViolation test failure by swapping

- core/pom.xml
- core/src/test/java/org/everit/json/schema/ObjectSchemaTest.java
This PR addresses issue #515 
I ran mvn edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.everit.json.schema.ObjectSchemaTest#toStringWithUnprocessedProps -DfailIfNoTests=false and notice test failure.
For the test: toStringWithUnprocessedProps, the usage of sameJsonAs function, which eventually uses the function deepEqualArrays, enforces strict order of the data in the Json files, making it a potential flaky test.
The fix utilizes [JSONAssert](https://github.com/skyscreamer/JSONassert) which compares Jsons but forgive ordering of the data.
> Fix flaky test toStringWithUnprocessedProps

- core/src/main/java/org/everit/json/schema/CombinedSchema.java
- core/src/main/java/org/everit/json/schema/ToStringVisitor.java
- core/src/test/java/org/everit/json/schema/ToStringTest.java
When converting a Schema to a string, if a synthetic allOf schema has multiple subschemas of the same criterion, then emit the allOf to prevent `org.json.JSONException: Duplicate key "anyOf"`
Fixes https://github.com/everit-org/json-schema/issues/520
> Handle multiple anyOf subschemas in ToStringVisitor

- core/src/main/java/org/everit/json/schema/CombinedSchema.java
- core/src/main/java/org/everit/json/schema/ValidatingVisitor.java
- core/src/test/java/org/everit/json/schema/CombinedSchemaTest.java
Maintain insertion order for subschemas of CombinedSchema.
This is an alternative to https://github.com/everit-org/json-schema/pull/519 that maintains the subschemas in insertion order.
The subschemas were originally maintained in insertion order, but it was changed due to https://github.com/everit-org/json-schema/pull/405, which ensured that subschemas that were of type CombinedSchema were visited first during validation, and by https://github.com/everit-org/json-schema/pull/498, which tries to maintain a stable order for "equivalent" instances.
This PR simply restores the insertion order, but maintains an internally sorted collection for the two purposes listed above, namely visiting subschemas during validation and equivalence checks during equals/hashCode.
> Maintain insertion order for subschemas of CombinedSchema
